SQL (Create Table) using Oracle APEX
DOCTOR:
CREATE TABLE DOCTOR(
DID int PRIMARY KEY,
FName VARCHAR(10) ,
LName VARCHAR(10),
Gender VARCHAR(10),
Address VARCHAR(15),
DType VARCHAR(10),
Department_ID int ,
FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT (Department_ID));
NURSE:
CREATE TABLE NURSE(
NID int PRIMARY KEY,
FName VARCHAR(10) ,
LName VARCHAR(10),
Gender VARCHAR(10),
Address VARCHAR(15),
NType VARCHAR(10),
Department_ID int ,
FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT (Department_ID));
RECEPTIONIST:
CREATE TABLE RECEPTIONIST(
RID int PRIMARY KEY,
FName VARCHAR(10) ,
LName VARCHAR(10),
Gender VARCHAR(10),
Address VARCHAR(15),
RType VARCHAR(10),
Department_ID int ,
FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT (Department_ID));
MEDICAL_RECORD:
CREATE TABLE MEDICAL_RECORD(
MR_Num int PRIMARY KEY,
Desrciption VARCHAR(20) ,
Patient_ID int,
RID int,
FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
FOREIGN KEY (RID) REFERENCES RECEPTIONEST(RID));
APPOINTMENT:
CREATE TABLE APPOINTMENT(
Serial_Num int primary key,
Date_Time timestamp,
Room_ID int,
RID int,
FOREIGN KEY (Room_ID) REFERENCES ROOM (Room_ID),
FOREIGN KEY (RID) REFERENCES RECEPTIONIST (RID));
DRUG:
CREATE TABLE DRUG(
Code int PRIMARY KEY,
Name VARCHAR(10) ,
Type VARCHAR(10),
DID int,
Patient_ID int,
FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID),
FOREIGN KEY (DID) REFERENCES DOCTOR(DID) );
PATIENT:
CREATE TABLE PATIENT(
Patient_ID int PRIMARY KEY,
FName VARCHAR(10),
LName VARCHAR(10),
Age int,
DOB DATE,
Phone_ID int,
MR_Num int,
FOREIGN KEY (MR_Num) REFERENCES MEDICAL_RECORD(MR_Num));
PHONE_NUMBER:
CREATE TABLE PHONE_NUMBER(
Phone_ID int,
Patient_ID int,
Num VARCHAR(8),
PRIMARY KEY(Phone_ID,Patient_ID));
ROOM
CREATE TABLE ROOM(
Room_ID int PRIMARY KEY,
Period varchar(5),
type varchar(15),
Department_ID int,
FOREIGN KEY (Department_ID) REFERENCES DEPARTMENT (Department_ID));
DEPARTMENT
CREATE TABLE DEPARTMENT (
Department_ID int PRIMARY KEY,
Location VARCHAR(15),
Type VARCHAR(15) );
PHONE_NUMBER:
CREATE TABLE PHONE_NUMBER(
Phone_ID int,
Patient_ID int,
Num VARCHAR(8),
PRIMARY KEY(Phone_ID,Patient_ID));
D_CONSULT_P
CREATE TABLE D_CONSULT_P(
DID int,
Patient_ID int,
Date_Time timestamp,
PRIMARY KEY(DID,Patient_ID));
N_GOVERNS_R
CREATE TABLE N_GOVERNS_R(
NID int,
Room_ID int,
Date_Time timestamp,
PRIMARY KEY(NID,Room_ID));
D_FILL_MR
CREATE TABLE D_FILL_MR(
DID int,
MR_Num int,
MR_Type VARCHAR(10),
PRIMARY KEY(DID,MR_NUM)
);
